name: bbbae_dualarm_erase_board_no_wrench

image_shape: [3, 224, 224]
dataset_path: data/baetae/260519/diffusion_data_height_wrench_encoder_R_image_current_pose_action_real.hdf5

# relative
low_dim_obs_horizon: 2
img_obs_horizon: 2
action_horizon: 16
ignore_proprioception: False

shape_meta: &shape_meta
  obs:
    image0:   # Head camera 242422304502
      shape: [3, 224, 224]
      type: rgb
      horizon: ${task.img_obs_horizon}
      
    #image1:   # Front camera 336222070518
    #  shape: [3, 240, 320]
    #  type: rgb
    
    #robot_pose_L:
    #  shape: [3]
    #  type: low_dim
    #robot_quat_L:
    #  shape: [4]
    #  type: low_dim
    
    robot_pose_R:
      shape: [3]
      type: low_dim
      horizon: ${task.low_dim_obs_horizon}
      
    robot_quat_R:
      shape: [4]
      type: low_dim
      horizon: ${task.low_dim_obs_horizon}
      rotation_rep: rotation_6d
      
    #hand_pose_L:
    #  shape: [7]
    #  type: low_dim
    
    #hand_pose_R:
    #  shape: [11]
    #  type: low_dim
    #  horizon: ${task.low_dim_obs_horizon}
      
    #wrench_wrist_R:
    #  shape: [6, 32]
    #  type: wrench
      
    #wrench_thumb_R:
    #  shape: [1, 32]
    #  type: wrench
      
    #wrench_index_R:
    #  shape: [1, 32]
    #  type: wrench
      
    #wrench_middle_R:
    #  shape: [1, 32]
    #  type: wrench
      
    #wrench_ring_R:
    #  shape: [1, 32]
    #  type: wrench
      
    #wrench_baby_R:
    #  shape: [1, 32]
    #  type: wrench
    
  action: 
    shape: [9] # robot_pose_R[3] + robot_rot6d_R[6] 
    horizon: ${task.action_horizon}
    rotation_rep: rotation_6d

pose_repr: &pose_repr
  obs_pose_repr: abs # abs or relative
  action_pose_repr: relative # abs or relative 
  
env_runner:
  _target_: diffusion_policy.env_runner.real_pusht_image_runner.RealPushTImageRunner

dataset:
  _target_: diffusion_policy.dataset.bae_robomimic_replay_image_dataset.BaeRobomimicReplayDataset
  shape_meta: *shape_meta
  dataset_path: ${task.dataset_path}
  horizon: ${horizon}
  # pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  # n_latency_steps: ${n_latency_steps}
  use_cache: True
  seed: 42
  val_ratio: 0.00
  # max_train_episodes: null
  # delta_action: False
  pose_repr: *pose_repr
  #abs_action: True
